spring:
  profiles:
    active: local
  jwt:
    secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  freemarker:
    cache: false

#logging:
#  level:
#    root: debug
